# Health Stats Part 4: Waist 2 Hip Ratios - Pandas Only

<!--- Write an explanation of the Waist To Hips Ratio statistic used by health professionals. Please include an explanation of what it is used for, exactly how it is calculated, and how to interpret the results. Note: Formmatting matters. Make this as professional as you can using Markdown.  --->
EDIT THIS MARKDOWN CELL

Waist to Hips Ratio: It measures the ratio of your waist circumference to your hip circumference.The waist-to-hip ratio (WHR) is a quick measure of fat distribution that may help indicate a person's overall health. People who carry more weight around their middle than their hips may be at a higher risk of developing certain health conditions.

<!--- feel free to use any web resources, including [Wikipedia](https://en.wikipedia.org/wiki/Waist%E2%80%93hip_ratio) or any other resources that you can find online. Just MAKE SURE you provide a link to every resource you decide to use. --->

Link:https://www.medicalnewstoday.com/articles/319439.php

<!--- Including the formula, or that fancy diagram/table you see on wikipedia is DEFINITELY a good idea! How? The LaTeX equations section in [This link](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html) might help. --->

 | Health risk | Men | Women |
 | ------- | ------- | ----- |
 | Low | 0.95 or lower | 0.80 or lower |
 | ------- | ------- | ----- |
 | Moderate | 0.96-1.0 | 0.81-0.85 |
 | ------- | ------- | ----- |
 | High | 1.0 or higher | 0.86 or higher |
 
 

$ ratio_{w2h} = \frac{w}{h} $

<!--- For extra points, try to create a table similar to the one on the wikipedia page on your own. --->

## Source Data

<!--- Replace the text below with a Markdown bullet list that defines the columns of the CSV file. Be sure to indicate the data type for each column. --->
EDIT THIS MARKDOWN CELL

W2H Ratio
- **ID**: unique identifier of each person, integer
- **Waist**: measurement of participant's waist circumfrence (cm), integer
- **Hip**: measurement of participant's hip circumfrence (cm), integer
- **Gender**: male or female, string
- **Shape**: WHO metric of body shap determined by W2H ratio, string

## Data Import

In [49]:
# Goal: Extract the data from the file

# use proper pandas function to read data from a CSV file to a DataFrame

import pandas as pd
datafile=pd.read_csv('w2h_data.csv')
datafile.head()

   ID  Waist  Hip Gender
0   1     30   32      M
1   2     32   37      M
2   3     30   36      M
3   4     33   39      M
4   5     29   33      M

## Calculations

In [50]:
# Goal: For each row of data calculate and store the w2h_ratio and shape.

# Step 1: Make sure the columns are in correct data types - refer to previous parts for the correct data types

# Step 2: calculate the 'W2H_Ratio' column using the 'Waist' and 'Hip' columns

# Step 3: Create the `Shape` column based on the values of the `W2H_Ratio` column - refer to previous parts for the logic

In [66]:
#Step 1: Make sure the columns are in correct data types - refer to previous parts for the correct data types
datafile.dtypes  #waist and hip are integers, so we do not need to change the data types

# Step 2: calculate the 'W2H_Ratio' column using the 'Waist' and 'Hip' columns
datafile['W2h_Ratio'] = datafile['Waist']/datafile['Hip']
#datafile.head() #tested the new column W2h_ratio

# Step 3: Create the `Shape` column based on the values of the `W2H_Ratio` column - refer to previous parts for the logic
datafile.loc[(datafile.Gender == 'M') & (datafile['W2h_Ratio'] > 0.9) | (datafile.Gender == 'F') & (datafile['W2h_Ratio'] > 0.8), 'shape'] = 'Apple'
datafile.loc[(datafile.Gender == 'M') & (datafile['W2h_Ratio'] <= 0.9) | (datafile.Gender == 'F') & (datafile['W2h_Ratio'] <= 0.8), 'shape'] = 'Pear'
#datafile  #tested the shape column values

    ID  Waist  Hip Gender  W2h_Ratio  shape
0    1     30   32      M   0.937500  Apple
1    2     32   37      M   0.864865   Pear
2    3     30   36      M   0.833333   Pear
3    4     33   39      M   0.846154   Pear
4    5     29   33      M   0.878788   Pear
5    6     32   38      M   0.842105   Pear
6    7     33   42      M   0.785714   Pear
7    8     30   40      M   0.750000   Pear
8    9     30   37      M   0.810811   Pear
9   10     32   39      M   0.820513   Pear
10  11     24   35      F   0.685714   Pear
11  12     25   37      F   0.675676   Pear
12  13     24   37      F   0.648649   Pear
13  14     22   34      F   0.647059   Pear
14  15     26   38      F   0.684211   Pear
15  16     26   37      F   0.702703   Pear
16  17     25   38      F   0.657895   Pear
17  18     26   37      F   0.702703   Pear
18  19     28   40      F   0.700000   Pear
19  20     23   35      F   0.657143   Pear

## Output

In [68]:
# Goal: pretty print the rows as an HTML table
# Display the complete DF
datafile
# Save the DF to a file './complete_w2h.csv'

    ID  Waist  Hip Gender  W2h_Ratio  shape
0    1     30   32      M   0.937500  Apple
1    2     32   37      M   0.864865   Pear
2    3     30   36      M   0.833333   Pear
3    4     33   39      M   0.846154   Pear
4    5     29   33      M   0.878788   Pear
5    6     32   38      M   0.842105   Pear
6    7     33   42      M   0.785714   Pear
7    8     30   40      M   0.750000   Pear
8    9     30   37      M   0.810811   Pear
9   10     32   39      M   0.820513   Pear
10  11     24   35      F   0.685714   Pear
11  12     25   37      F   0.675676   Pear
12  13     24   37      F   0.648649   Pear
13  14     22   34      F   0.647059   Pear
14  15     26   38      F   0.684211   Pear
15  16     26   37      F   0.702703   Pear
16  17     25   38      F   0.657895   Pear
17  18     26   37      F   0.702703   Pear
18  19     28   40      F   0.700000   Pear
19  20     23   35      F   0.657143   Pear

In [69]:
# Save the DF to a file './complete_w2h.csv'
datafile.to_csv(r'./complete_w2h.csv')

## Lessons Learned

Have you noticed in the previous two parts, how much code we have written? Have you also note how little code we have written in this part, with the help of Pandas? 

This is the reason why we want to use Pandas to handle the data we use for analytics.

In [ ]:
Pandas required less coding when compared to Python.